all:
  vars:
#     ansible_ssh_private_key_file: /home/ubuntu/file.pem
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: ubuntu
          hostname: AnsibleMaster
    prod:
      vars:
        ansible_password: ubuntu
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

      hosts:
        worker01:
          ansible_host: 172.31.86.160
          ansible_user: ubuntu
          hostname: AnsibleWorker01

        worker02:
          ansible_host: 172.31.95.133
          ansible_user: ubuntu
          hostname: AnsibleWorker02

        worker03:
          ansible_host: 172.31.94.16
          ansible_user: centos
          hostname: AnsibleWorker03
