---
- name: "Installl Docker"
  hosts: "prod"

    tasks:
    - name: "Get docker script"
      command: "curl -fsSL https://get.docker.com"
        dest: "/tmp/get-docker.sh"
      
    - name: "Run install script"
      command: "sh /tmp/get-docker.sh"
    
    - name: "Add ubuntu to docker group"
      command: "usermod -aG docker {{ ansible_user }}"

    - name: 'Install pip'
      package:
        name: "python3-pip"
        state: "present"

    - name: "Install docker-py module"
      pip:
        name: "docker-py"
        state: "present"
