all:
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: "local"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_user: "ubuntu"
          hostname: "ansible-master"
    prod:
      hosts:
        worker01:
          ansible_host: "172.31.86.160"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_user: "ubuntu"
          hostname: "ansible-worker01"
          ansible_password: '{{ ansible_vault_password }}'

        worker02:
          ansible_host: "172.31.95.133"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_user: "ubuntu"
          hostname: "ansible-worker02"
          ansible_password: '{{ ansible_vault_password }}'
