---
- name: "Install docker"
  hosts: prod
  vars_files: secrets.yml
  tasks:
    - name: "Download Install docker script"
      get_url:
        url: "https://get.docker.com"
        dest: /home/ubuntu/get-docker.sh
      when: ansible_docker0 is undefined

    - name: "Run script to install docker"
      command: "sh /home/ubuntu/get-docker.sh"
      when: ansible_docker0 is undefined

    - name: "Give the privilège to ubuntu"
      user:
        name: ubuntu
        append: yes
        groups:
          - docker

    - name: "Install python pip"
      apt:
        name: python3-pip
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: "Install docker-py module"
      pip:
        name: docker-py
        state: present
